=== p19891117/webmagic/webmagic-core/src/main/resources/site.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://www.qysudu.com/site" 
		xmlns:tns="http://www.qysudu.com/site"
		elementFormDefault="qualified">
	<xs:element name="app" type="tns:apptype"/>
	
	<xs:complexType name="apptype">
		<xs:complexContent>
			<xs:extension base="tns:comm_att_desc">
				<xs:sequence>
					<xs:element name="site" type="tns:spidertype" minOccurs="1" maxOccurs="1"/>
					<xs:any minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="spidertype">
		<xs:complexContent>
			<xs:extension base="tns:comm_att_desc">
				<xs:sequence >
					<xs:element name="userAgent" type="xs:string" minOccurs="1" maxOccurs="1"/>
					<xs:element name="charset" type="xs:string" minOccurs="1" maxOccurs="1"/>
					<xs:element name="sleepTime" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="retryTimes" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="cycleRetryTimes" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="retrySleepTime" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="timeOut" type="xs:int" minOccurs="1" maxOccurs="1"/>
					<xs:element name="useGzip" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
					<xs:element name="Header" type="tns:headtype" minOccurs="1" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="headtype">
		<xs:sequence>
			<xs:element name="key-value" type="tns:key-valuetype" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="key-valuetype">
		<xs:attribute name="name"  type="xs:string" />
		<xs:attribute name="value"  type="xs:string" />
	</xs:complexType>
	<xs:complexType name="scripttype">
		<xs:sequence minOccurs="0" maxOccurs="unbounded" >
			<xs:element name="instance" type="tns:instancetype" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="instancetype">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="value" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="comm_att_desc">
		<xs:attribute name="desc" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== p19891117/webmagic/webmagic-core/src/main/resources/site-default.xml
<?xml version="1.0" encoding="UTF-8"?>
<s:app desc="采集程序配置文件"
	xmlns:s="http://www.qysudu.com/site" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.qysudu.com/site site.xsd ">
	<s:site desc="httpclient参数、http协议头">
		<s:userAgent>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0</s:userAgent>
		<s:charset>UTF-8</s:charset>
		<s:sleepTime>5000</s:sleepTime>
		<s:retryTimes>0</s:retryTimes>
		<s:cycleRetryTimes>0</s:cycleRetryTimes>
		<s:retrySleepTime>1000</s:retrySleepTime>
		<s:timeOut>5000</s:timeOut>
		<s:useGzip>true</s:useGzip>
		<s:Header>
			<s:key-value  name="User-Agent" value="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0" />
			<s:key-value  name="Accept" value="text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" />
			<s:key-value  name="Accept-Encoding" value="gzip, deflate" />
			<s:key-value  name="Accept-Language" value="zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3" />
			<s:key-value  name="Cache-Control" value="no-cache" />
			<s:key-value  name="Connection" value="keep-alive" />
			<s:key-value  name="Content-Type" value="application/x-www-form-urlencoded; charset=UTF-8" />
		</s:Header>
	</s:site>
</s:app>
